# Generated by Django 3.2.9 on 2021-11-21 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('EL', 'Earned Leave')], default='SL', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=200, verbose_name='Remarks')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('description', models.CharField(max_length=200, verbose_name='Remarks')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_licensed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-category', '-name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=100)),
                ('is_licensed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='pckgs.software')),
            ],
        ),
    ]
