# Generated by Django 3.2.9 on 2021-11-21 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pckgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='req',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pckgs.software'),
        ),
        migrations.AddField(
            model_name='req',
            name='raised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_by2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='req',
            name='version_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versionname', to='pckgs.version'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='raised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_by1', to=settings.AUTH_USER_MODEL),
        ),
    ]
